name: Build Typst Document
on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    # - uses: actions/checkout@v3
    # - uses: DeterminateSystems/nix-installer-action@main
    # - uses: DeterminateSystems/magic-nix-cache-action@main
    # - run: echo "$(TZ="Europe/Berlin" date +"%Y-%m-%d %H:%M:%S")" > document/utils/build-datetime.typ
    # - run: mkdir out
    # - run: nix run github:typst/typst/v0.8.0 -- compile document/main.typ out/SAil_ARrrr_Documentation.pdf
    # - run: nix run github:typst/typst/v0.8.0 -- compile document/content/meeting-minutes/week01.typ out/week01.pdf
    # - run: nix run github:typst/typst/v0.8.0 -- compile document/content/meeting-minutes/week02.typ out/week02.pdf
    # - run: nix run github:typst/typst/v0.8.0 -- compile document/content/meeting-minutes/week03.typ out/week03.pdf
    # - run: mv index.html out/index.html
    # - uses: actions/upload-pages-artifact@v1
      # with: { path: 'out' }
      - uses: actions/checkout@v3      
      - run: echo "$(TZ="Europe/Berlin" date +"%Y-%m-%d %H:%M:%S")" > document/utils/build-datetime.typ
      - uses: lvignoli/typst-action@main
        with:
          source_file: |
            document/main.typ
            document/content/meeting-minutes/week01.typ
            document/content/meeting-minutes/week02.typ
            document/content/meeting-minutes/week03.typ
      - run: mkdir out
      - run: mv index.html out/index.html
      - run: mv document/main.pdf out/SAil_ARrrr_Documentation.pdf
      - run: mv document/content/meeting-minutes/week01.pdf out/week01.pdf
      - run: mv document/content/meeting-minutes/week02.pdf out/week02.pdf
      - run: mv document/content/meeting-minutes/week03.pdf out/week03.pdf
      - uses: actions/upload-pages-artifact@v1
        with: { path: 'out' }

  Deploy:
    name: Deploy
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: Build
    concurrency:
      group: "pages"
      cancel-in-progress: false
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2