name: Build Typst Document
on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3      
      - run: echo "$(TZ="Europe/Berlin" date +"%Y-%m-%d %H:%M:%S")" > utils/build-datetime.typ
      - uses: lvignoli/typst-action@main
        with:
          source_file: |
            main.typ
            chapters/appendix/meeting-minutes/week01.typ
            chapters/appendix/meeting-minutes/week02.typ
            chapters/appendix/meeting-minutes/week03.typ
            chapters/appendix/meeting-minutes/week04.typ
            chapters/appendix/meeting-minutes/week05.typ
            chapters/appendix/meeting-minutes/week06.typ
            chapters/appendix/meeting-minutes/week07.typ
            chapters/appendix/meeting-minutes/week08.typ
            chapters/appendix/meeting-minutes/week09.typ
            chapters/appendix/meeting-minutes/week10.typ
            chapters/appendix/meeting-minutes/week11.typ
            chapters/appendix/meeting-minutes/week12.typ
            chapters/appendix/meeting-minutes/week13.typ
            chapters/appendix/meeting-minutes/week14.typ
      - run: mkdir out
      - run: mv index.html out/
      - run: mv main.pdf out/SAil_ARrrr_Documentation.pdf
      - run: mv chapters/appendix/meeting-minutes/week*.pdf out/
      - uses: actions/upload-pages-artifact@v1
        with: { path: 'out' }

  Deploy:
    name: Deploy
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: Build
    concurrency:
      group: "pages"
      cancel-in-progress: false
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2